# Usamos a imagem completa do Node para ter todas as ferramentas
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de pacotes
COPY package.json package-lock.json ./

# Instala as dependências. O cache do npm será mantido no contêiner
# para agilizar futuras inicializações.
RUN npm install

# Copia o resto do código da sua aplicação
COPY . .

# Expõe a porta padrão do servidor de desenvolvimento do Angular
EXPOSE 4200

# O comando padrão para iniciar o container será 'npm start' (que executa 'ng serve')
CMD ["npm", "start"]
